[package]
name = "branch-info"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
gix = { path = "../gix", default-features = false, features = ["revision"] }

[lints]
workspace = true
