[alias]
build-short = "build --message-format short"
check-short = "check --message-format short"
test-short = "test --message-format short"
run-short = "run"
clippy-short = "clippy --message-format short"
